# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 13:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Business legal name')),
                ('phone', models.CharField(max_length=21, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+\\d{7,20}$')], verbose_name='Business phone')),
                ('contact', models.CharField(max_length=256, verbose_name='Business contact')),
                ('number_service_trucks', models.CharField(max_length=256, verbose_name='Number of Service Trucks')),
                ('number_service_pros', models.CharField(max_length=256, verbose_name='Number of Service Pros in the field')),
                ('current_merchant', models.CharField(max_length=256, verbose_name='Current Merchant Processing Provider')),
                ('average_yrb', models.CharField(max_length=256, verbose_name='Average Yearly Revenue of Business')),
                ('average_yrt', models.CharField(max_length=256, verbose_name='Average Yearly Revenue of Credit/Debit Transactions')),
                ('average_ymb', models.CharField(max_length=256, verbose_name='Average Monthly Revenue of Business')),
                ('average_ymt', models.CharField(max_length=256, verbose_name='Average Monthly Revenue of Credit/Debit Transactions')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='MethodAcceptingCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.PositiveSmallIntegerField(choices=[(1, 'physical terminal'), (2, 'mobile card readers'), (3, 'mobile app'), (4, 'virtual internet terminal'), (5, 'phone')], unique=True, verbose_name='method')),
            ],
            options={
                'verbose_name': 'Method of accepting cards',
                'verbose_name_plural': 'Methods of accepting cards',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='current_method_cards',
            field=models.ManyToManyField(to='companies.MethodAcceptingCards', verbose_name='Current Method of accepting Credit Cards and/or Debit Cards'),
        ),
    ]
