# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='agree'),
        ),
    ]
