# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='agreement_2',
            field=models.BooleanField(default=False, help_text='By clicking here - you agree that you will process all of your businesses credit and debit transactions with Service.com and in exchange you will receive the benefit of Service.com paying for your Service Pros Cell Phone Bills', verbose_name='Agree 2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='agreement',
            field=models.BooleanField(default=False, help_text='Agree to the Terms of Service and Privacy Policy', verbose_name='Agree 1'),
        ),
    ]
