# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import utils.uploads


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20160125_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cellbills',
            field=models.ImageField(blank=True, upload_to=utils.uploads.upload_to, verbose_name='Merchant processing'),
        ),
        migrations.AddField(
            model_name='company',
            name='merchantbills',
            field=models.ImageField(blank=True, upload_to=utils.uploads.upload_to, verbose_name='Corporate cell phone bill'),
        ),
    ]
