# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import utils.aws
import utils.uploads


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20160125_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cellbills',
            field=models.ImageField(blank=True, storage=utils.aws.SerializeS3BotoStorage(bucket_name=b'newform'), upload_to=utils.uploads.upload_to, verbose_name='Merchant processing'),
        ),
        migrations.AlterField(
            model_name='company',
            name='merchantbills',
            field=models.ImageField(blank=True, storage=utils.aws.SerializeS3BotoStorage(bucket_name=b'newform2'), upload_to=utils.uploads.upload_to, verbose_name='Corporate cell phone bill'),
        ),
    ]
